title: Guacamaya Lab
description: An online notebook — unfinished, evolving, honest.
theme: jekyll-theme-minimal

author: Yatan

permalink: /:year/:month/:day/:title/

markdown: kramdown

plugins:
  - jekyll-feed

sass:
  style: compressed

show_downloads: false

github:
  is_project_page: false

lang: en

url: "https://guacamayalab.com"