baseURL: 'https://www.yatanco.com'
defaultContentLanguage: en
languageCode: en
title: Yatan Blumenthal Vargas
theme: PaperMod

params:
 params:
    homeInfoParams:
        Title: Yatan Blumenthal Vargas
        Content: A polymath interested in things

    socialIcons: # optional
        - name: github
          url: yatanco
        - name: instagram
          url: yatanbv
  

menu:
  main:
    - identifier: mywork
      pre: ''
      post: ''
      name: My Work
      url: /work/
      title: ''
      weight: 1
    - identifier: posts
      pre: ''
      post: ''
      name: Blog
      url: /posts/
      title: ''
      weight: 1
    - identifier: meditation
      pre: ''
      post: ''
      name: Meditations
      url: /meditation/
      title: ''
      weight: 1
    - identifier: categories
      pre: ''
      post: ''
      name: Categories
      url: /categories/
      title: ''
      weight: 3
      # that dropdown thang
    
markup:
  highlight:
    noClasses: false
